const labels: Record<string, string> = {
  ADMIN: "Administrador",
  MARKETING: "Marketing",
  VENTAS: "Ventas",
  LECTURA: "Solo lectura",
  NUEVO: "Nuevo",
  CONTACTADO: "Contactado",
  OPORTUNIDAD: "Oportunidad",
  CLIENTE: "Cliente",
  DESCARTADO: "Descartado",
  PENDIENTE: "Pendiente",
  VENCIDO: "Vencido",
  COMPLETADO: "Completado",
  PROGRAMADO: "Programado",
  ENVIADO: "Enviado",
  FALLIDO: "Fallido",
  BORRADOR: "Borrador",
  PUBLICADO: "Publicado",
  ACTIVO: "Activo",
  INACTIVO: "Inactivo",
  REAL: "Real",
  TEST: "Prueba técnica",
  DEMO: "Demostración",
  UNKNOWN: "Por clasificar",
  DRAFT: "Borrador",
  ACTIVE: "Activa",
  PAUSED: "Pausada",
  ARCHIVED: "Archivada",
  ON_REGISTRATION: "Al registrarse",
  BEFORE_COURSE: "Antes del curso",
  AFTER_COURSE: "Después del curso",
  ACEPTADO: "Aceptado por proveedor",
  ENTREGADO: "Entregado",
  REBOTADO: "Rebotado",
  NEVER_SYNCED: "Sin sincronizar",
  SYNCED: "Sincronizado",
  CONFLICT: "Conflicto",
  ERROR: "Error",
  SIMULATION: "Simulación",
  READY: "Conexión validada",
  EXPIRED: "Token vencido",
  DISCONNECTED: "Desconectada",
  MISSING_PERMISSION: "Permisos insuficientes",
  ARCHIVADO: "Archivado",
  ELIMINADO_LOCAL: "Eliminado localmente",
  ELIMINADO_PROVEEDOR: "Eliminado en proveedor",
  EMAIL: "Correo electrónico",
  WHATSAPP: "WhatsApp",
  TELEFONO: "Teléfono",
  MATCH: "Coincidente",
  MISSING_IN_CRM: "Falta en el CRM",
  EXTRA_IN_CRM: "Histórico o sobrante",
  DIFFERENT: "Datos distintos",
  AdminUser: "Usuario administrativo",
  Course: "Curso",
  CourseCatalog: "Catálogo de cursos",
  Lead: "Contacto",
  Enrollment: "Inscripción",
  FollowUp: "Seguimiento",
  OutboundMessage: "Mensaje",
  SocialAccount: "Cuenta social",
  SocialPost: "Publicación social",
  SocialSchedule: "Recurrencia social",
  MessageTemplate: "Plantilla de mensaje",
  Campaign: "Campaña",
  AutomationRule: "Regla de automatización",
  CatalogSyncRun: "Sincronización de catálogo",
  Session: "Sesión",
  AUTH_LOGIN: "Inicio de sesión",
  AUTH_LOGIN_LEGACY: "Inicio de sesión heredado",
  AUTH_LOGOUT: "Cierre de sesión",
  ADMIN_USER_CREATED: "Usuario creado",
  ADMIN_USER_UPDATED: "Usuario actualizado",
  LEADS_EXPORTED: "Contactos exportados",
  LEAD_CREATED: "Contacto creado",
  LEAD_CREATED_MANUALLY: "Contacto creado manualmente",
  LEAD_UPDATED: "Contacto actualizado",
  LEAD_ARCHIVED: "Contacto archivado",
  LEAD_RESTORED: "Contacto restaurado",
  LEAD_CLASSIFICATION_CHANGED: "Clasificación actualizada",
  LEAD_TEST_DELETED: "Registro de prueba eliminado",
  LEAD_STAGE_CHANGED: "Etapa comercial actualizada",
  COURSE_CREATED: "Curso creado",
  COURSE_UPDATED: "Curso actualizado",
  COURSE_DEACTIVATED: "Curso desactivado",
  COURSE_CATALOG_IMPORTED: "Catálogo oficial importado",
  COURSE_CATALOG_IMPORT_NO_CHANGES: "Catálogo oficial verificado sin cambios",
  COURSE_CATALOG_HISTORICAL_DEACTIVATED: "Curso histórico desactivado",
  FINANCE_HANDOFF: "Envío preparado para Finance",
  FINANCE_HANDOFF_SIMULATED: "Envío a Finance simulado",
  MESSAGE_CANCELLED: "Mensaje cancelado",
  MESSAGE_RETRIED: "Mensaje reintentado",
  MESSAGE_SIMULATED: "Mensaje simulado",
  MESSAGE_OMITTED: "Mensaje omitido",
  MESSAGE_PROVIDER_ACCEPTED: "Mensaje aceptado por proveedor",
  MESSAGE_PROVIDER_FAILED: "Fallo de proveedor de mensajes",
  MESSAGE_PROVIDER_STATUS_UPDATED: "Estado de entrega actualizado",
  AUTOMATION_MESSAGES_QUEUED: "Mensajes automáticos programados",
  AUTOMATION_SCHEDULING_FAILED: "Fallo al programar automatización",
  AUTOMATION_RULE_CREATED: "Automatización creada",
  AUTOMATION_RULE_UPDATED: "Automatización actualizada",
  AUTOMATION_RULE_DELETED: "Automatización eliminada",
  CAMPAIGN_CREATED: "Campaña creada",
  CAMPAIGN_UPDATED: "Campaña actualizada",
  CAMPAIGN_ARCHIVED: "Campaña archivada",
  SOCIAL_ACCOUNT_SAVED: "Cuenta social guardada",
  SOCIAL_ACCOUNT_UPDATED: "Cuenta social actualizada",
  SOCIAL_ACCOUNT_DEACTIVATED: "Cuenta social desactivada",
  SOCIAL_POST_CREATED: "Publicación creada",
  SOCIAL_POST_PUBLISH_REQUESTED: "Publicación solicitada",
  SOCIAL_POST_DELETED_LOCAL: "Publicación local eliminada",
  SOCIAL_CONNECTION_CHECKED: "Conexión social comprobada",
  WORDPRESS_CATALOG_SYNCED: "Catálogo WordPress sincronizado",
  WORDPRESS_CATALOG_SYNC_FAILED: "Sincronización WordPress fallida",
  SOCIAL_SCHEDULE_CREATED: "Recurrencia creada",
  FOLLOW_UP_CREATED: "Seguimiento creado",
  FOLLOW_UP_UPDATED: "Seguimiento actualizado",
  FOLLOW_UP_RESCHEDULED: "Seguimiento reprogramado",
};

export function presentAdminValue(value: string | null | undefined) {
  if (!value) return "—";
  if (labels[value]) return labels[value];
  const normalized = value.replaceAll("_", " ").toLocaleLowerCase("es");
  return normalized.charAt(0).toLocaleUpperCase("es") + normalized.slice(1);
}
